### ISSUE TITLE
Fatal error after updating to WP 5.5

### ISSUE THREAD

**Issue by senlin** [senlin/so-clean-up-wp-seo#88]
There have been reports of a Fatal Error occurring after updating WP to version 5.5

## Expected behavior
Everything works as it should

## Current behavior
```
PHP Fatal error:  Uncaught Error: Closure object cannot have properties in /home/*/public_html/wp-includes/class-wp-list-util.php:115
Stack trace:
#0 /home/*/public_html/wp-includes/functions.php(4564): WP_List_Util->filter(Array, 'AND')
#1 /home/*/public_html/wp-content/plugins/so-clean-up-wp-seo/includes/remove-class.php(28): wp_list_filter(Array, Array)
#2 /home/*/public_html/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php(246): remove_class_hook('admin_notices', 'WPSEO_Admin_Ini...', 'permalink_setti...')
```

**Comment by senlin** [comment]
I have tried to reproduce this and so far have not been able to, so if you experience this issue, please give context (theme/plugins/PHP version/anything that might help to get to the core of the problem).

**Comment by knutsp** [comment]
Please try with the Blocky theme. Reported to Blocksy. Was not a problem under WP 5.4. May be we can find out what kind of interference or collssion this is.

**Comment by senlin** [comment]
I have tried updating on several sites including live client sites, no problem.

> Please try with the Blocky theme

Sorry, I don't think that I have to test a plugin with each and every theme out there.

**Comment by andreiglingeanu** [comment]
Hi @senlin,

One of the Blocksy developers here. Here I've tried to outline the situation in more details: https://wordpress.org/support/topic/fatal-error-with-wp-5-5-and-spcific-plugin/#post-13239538

It looks like in your implementation if `remove_class_hook()` you don't consider the case that a hook can be an anonymous function.

Our admin notices are added like this:

```php
add_action('admin_notices', function () {
	// Code for adding notices
});
```

I understand that you weren't able to prevent this but I'm happy to contribute a fix or test your solution before you push an update so that everyone can benefit from it.

**Comment by knutsp** [comment]
You don't have to do anything. I sometimes do things I don't have to, because it's interesting, learning, and helping our users. The trace seems to indicate this plugin does something that triggers it.

I may report back here if I find out what is happening, with how many themes or other plugins. But I don't have to.

**Comment by andreiglingeanu** [comment]
Thanks for the work on reporting this both ways @knutsp. I'm happy to contribute a solution to the matter if @senlin is willing to accept & release it.

**Comment by senlin** [comment]
@andreiglingeanu - we added that specific function a year ago (https://github.com/senlin/so-clean-up-wp-seo/blob/develop/includes/remove-class.php which contains an explanation). If you know of another way of making that specific function work, then by all means; I'd be happy to release your patch.

**Comment by senlin** [comment]
The author (@Dibbyo456) of the function is also https://github.com/senlin/so-clean-up-wp-seo/issues/71#issuecomment-672297686.

**Comment by senlin** [comment]
Many thanks @andreiglingeanu for your patch. I will soon release the patch over at WP.

**Comment by senlin** [comment]
WP 3.14.3 released over at WP, thanks again @andreiglingeanu
